title: "Jin Woong의 개발 블로그"
description: "홍진웅의 개인 개발 블로그 — 알고리즘·CS 개념 정리 및 Java 예제"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

collections:
  algorithms:
    output: true
    permalink: /algorithms/:name/

nav:
  - title: Algorithms
    url: /algorithms/
